---
- name: Cisco show version example
  hosts: routers
  gather_facts: false
  tasks:
    - name: run show version on the routers
      ios_command:
        commands: show ip int bri
      register: output
    - name: print output
      debug:
        var: output.stdout_lines
